// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcAe7kMDm0Uk7Hrggh8WkG3iOmqC2Uvl4',
    appId: '1:552440032442:web:efa6f7ae25a81f9330a683',
    messagingSenderId: '552440032442',
    projectId: 'nounou-express-2112b',
    authDomain: 'nounou-express-2112b.firebaseapp.com',
    storageBucket: 'nounou-express-2112b.firebasestorage.app',
    measurementId: 'G-M81N8RGX8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChXgTuKfkZA-MP9QlO6Mj-KID5YSBmFVk',
    appId: '1:552440032442:android:09111215d25ebae630a683',
    messagingSenderId: '552440032442',
    projectId: 'nounou-express-2112b',
    storageBucket: 'nounou-express-2112b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7oMOTLAVtdZibvreePZOeEv6OO7WJ26E',
    appId: '1:552440032442:ios:73fec98e3d44a4fc30a683',
    messagingSenderId: '552440032442',
    projectId: 'nounou-express-2112b',
    storageBucket: 'nounou-express-2112b.firebasestorage.app',
    iosBundleId: 'com.nounouexpress.nounouExpress',
  );
}
